<?php

namespace App\Filament\Pages\archivre;

use App\Models\ActeMariage;
use App\Models\DateMariage;
use Filament\Pages\Page;

class acte_mariage extends Page
{
    protected static ?string $navigationGroup = "Archivres";
    protected static ?string $title = "Acte de mariage";
    protected static ?string $navigationLabel = "Acte de mariage";

    protected static string $view = 'filament.pages.archivre.acte_mariage';

    public static function getNavigationBadge(): ?string
    {
        return ActeMariage::query()->where('status', 700)->count(); // TODO: Change the autogenerated stub
    }
}
