<?php

namespace App\Filament\Pages\archivre;

use App\Models\ActeDeces;
use App\Models\DateMariage;
use Filament\Pages\Page;

class acte_deces extends Page
{
    protected static ?string $navigationGroup = "Archivres";
    protected static ?string $title = "Acte de deces";
    protected static ?string $navigationLabel = "Acte de deces";
    protected static string $view = 'filament.pages.archivre.acte_deces';

    public static function getNavigationBadge(): ?string
    {
        return ActeDeces::query()->where('status', 700)->count(); // TODO: Change the autogenerated stub
    }
}
