<?php

namespace App\Filament\Pages\archivre;

use App\Models\ActeNaissance;
use Filament\Pages\Page;

class copie_acte_naissance extends Page
{
    protected static ?string $navigationGroup = "Archivres";
    protected static ?string $title = "Copie d'acte de naissance";
    protected static ?string $navigationLabel = "Copie d'acte de naissance";
    protected static string $view = 'filament.pages.archivre.copie_acte_naissance';

    public static function getNavigationBadge(): ?string
    {
        return ActeNaissance::query()->where('status', 700)->count(); // TODO: Change the autogenerated stub
    }
}
