<?php

namespace App\Filament\Pages\archivre;

use App\Models\DateMariage;
use App\Models\DeclarationNaissance;
use Filament\Pages\Page;

class declaration_acte_naissance extends Page
{
    protected static ?string $navigationGroup = "Archivres";
    protected static ?string $title = "Declaration d'acte de naissance";
    protected static ?string $navigationLabel = "Declaration d'acte de naissance";

    protected static string $view = 'filament.pages.archivre.declaration_acte_naissance';

    public static function getNavigationBadge(): ?string
    {
        return DeclarationNaissance::query()->where('status', 700)->count(); // TODO: Change the autogenerated stub
    }
}
