<?php

namespace App\Filament\Pages\archivre;

use App\Models\DateMariage;
use Filament\Pages\Page;

class reservation_date_mariage extends Page
{
    protected static ?string $navigationGroup = "Archivres";
    protected static ?string $title = "Réservation date de mariage";
    protected static ?string $navigationLabel = "Réservation date de mariage";

    protected static string $view = 'filament.pages.archivre.reservation_date_mariage';

    public static function getNavigationBadge(): ?string
    {
        return DateMariage::query()->where('status', 700)->count(); // TODO: Change the autogenerated stub
    }
}
